### ISSUE TITLE
POST to remixes endpoint doesn't create a record for the current user

### ISSUE THREAD

**Issue by toolness** [mozilla/api.webmaker.org#105] opened 2015-06-30 00:45 UTC
I was investigating https://github.com/mozilla/webmaker-android/issues/2300 and I think its cause is in this project. I could easily be wrong, though, as I've never looked at the code for this project *or* webmaker-android until today.

It seems that when a new project is created, a subpath of `/users/{user}` is contacted, where `{user}` is the currently logged-in user. This happens to result in [`prerequisites.getUser`](https://github.com/mozilla/api.webmaker.org/blob/a77cc9550c786b56c556525a980afa50c4619bcc/services/api/lib/prerequisites.js#L34-L62) being called, which notices that `{user}` doesn't exist and is the currently logged-in user, and then lazily creates it. The [`getTokenUser`](https://github.com/mozilla/api.webmaker.org/blob/a77cc9550c786b56c556525a980afa50c4619bcc/services/api/lib/prerequisites.js#L64-L90) immediately follows and succeeds, because a DB entry for the current user was just created.

However, when the logged-in user has *not* yet created a project, and instead chooses to remix an existing project, a POST request is issued to `/users/{user}/projects/{project}/remixes`. Here `{user}` is *not* the currently logged-in user--it's the user who created the project that the logged-in user wants to remix. This means that a record for the current user is *not* created, which means that `getTokenUser` fails with `"User not found"`.

If I'm correct, then I'm not sure what the best solution to the problem is. One is to modify `getTokenUser` to *also* lazily create the currently logged-in user if they can't be found, but I'm not sure if it's ideal, as I've never looked at this codebase until today.

**Comment by ashleygwilliams** [comment] 2015-06-30 15:17
i have a thought here and perhaps i'm missing something- but why such nested routes? if we have flat routes with ids that are unique throughout the whole system we could avoid a lot of this complexity?

**Comment by cadecairos** [comment] 2015-06-30 15:26
@ashleygwilliams I never liked the nested routes, they add an annoying amount of complexity.

Back in the early days of this project we went with the current structure for reasons I can't even recall.. we'd have to dig up old closed issues to find out

**Comment by ashleygwilliams** [comment] 2015-06-30 15:28
yeah, i'd be interested to see. i 100% think that ids unique to the entire projects with shallow routes is the better design and i'd be happy to help work on that (probably starting tomorrow) if we wanted to change it. changing it might help eliminate some of the errors that have been reported here in the last few days.

**Comment by cadecairos** [comment] 2015-06-30 15:35
That will be a pretty big lift, and as much as I'd like to see it happen, I'm not sure we want to go there at this point.

Since we've shipped Webmaker apks to the play store that use this route structure, we're committed to maintaining them.

**Comment by ashleygwilliams** [comment] 2015-06-30 16:00
we could create a new version of the API and ship with that... potentially align this with switching to the json-api standard...

**Comment by cadecairos** [comment] 2015-06-30 16:14
The solution to this issue is almost certainly not going to be to refactor the API, so lets file a new issue for that and get discussion rolling there.

I don't think it'll be too hard to get a user row created on remix with the current set of prereq functions available.

**Comment by cadecairos** [comment] 2015-06-30 21:18
@toolness I think I've got a fix for this, just need to write regression tests.

**Closed** 2015-07-02 16:19 UTC
